# Generated by Django 3.2 on 2022-03-24 11:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(default=10)),
                ('active', models.CharField(choices=[('active', 'active'), ('unactive', 'unactive')], default='active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('sku', models.CharField(max_length=100)),
                ('information', ckeditor.fields.RichTextField(null=True)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('regular_discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_charge', models.IntegerField(blank=True, null=True, verbose_name='Delivery Charge')),
                ('quantity', models.IntegerField(default=1)),
                ('stock_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out Stock', 'Out Stock')], default='In Stock', max_length=100)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=99, size=[400, 400], upload_to='product/image')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Free Shipping')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_duration', models.CharField(choices=[('', ''), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=100)),
                ('warranty_date', models.CharField(choices=[('', ''), ('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year')], default='', max_length=100)),
                ('warranty_type', models.CharField(choices=[('', ''), ('warranty', 'Warranty'), ('Guarantee', 'Guarantee')], default='', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=10, verbose_name='Product Attribute')),
                ('value', models.CharField(max_length=10, verbose_name=' Attribute Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGellary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=99, size=[400, 400], upload_to='product/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gellery', to='product.product')),
            ],
        ),
    ]
