# Generated by Django 3.2 on 2022-03-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_brand_subcategory_child'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory_child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory_child'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='attribute',
            field=models.CharField(max_length=10, verbose_name='Specification Name'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=10, verbose_name='Specification Value'),
        ),
    ]
