# Generated by Django 3.2 on 2022-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220325_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegellary',
            name='images',
            field=models.ImageField(upload_to='product/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/image'),
        ),
    ]
