# Generated by Django 3.2 on 2022-04-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_brand_subcategory_child'),
        ('product', '0004_alter_productspecification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subChildProduct', to='category.subcategory_child'),
        ),
    ]
