# Generated by Django 3.2 on 2022-03-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_brand_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='subcategory_child',
        ),
    ]
