# Generated by Django 3.2 on 2022-03-24 11:04

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_caption', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption 1')),
                ('last_captiop', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption 2')),
                ('action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call To Action Text')),
                ('action_url', models.CharField(max_length=100, verbose_name='Call To Action Url')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[450, 450], upload_to='product/banner/footer_banner')),
                ('types', models.CharField(blank=True, choices=[('New Deal', 'New Deal'), ('Hot Deal', 'Hot Deal'), ('New Arriavels', 'New Arriavels')], default='', max_length=100, null=True)),
                ('active', models.BooleanField(verbose_name='Open In Window')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_caption', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption 1')),
                ('last_captiop', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption 2')),
                ('action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call To Action Text')),
                ('action_url', models.CharField(max_length=100, verbose_name='Call To Action Url')),
                ('image', models.ImageField(upload_to='product/banner/header_banner')),
                ('active', models.BooleanField(verbose_name='Open In Window')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_caption', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption 1')),
                ('last_captiop', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption 2')),
                ('action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call To Action Text')),
                ('action_url', models.CharField(max_length=100, verbose_name='Call To Action Url')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=99, size=[990, 420], upload_to='product/banner/slider')),
                ('types', models.CharField(blank=True, choices=[('New Deal', 'New Deal'), ('Hot Deal', 'Hot Deal'), ('New Arriavels', 'New Arriavels')], default='', max_length=100, null=True)),
                ('active', models.BooleanField(verbose_name='Open In Window')),
            ],
        ),
    ]
