# Generated by Django 3.2 on 2022-03-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_brand_subcategory_child'),
        ('banner', '0002_alter_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call To Action Text')),
                ('action_url', models.CharField(max_length=100, verbose_name='Call To Action Url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/banner/footer_banner')),
                ('active', models.BooleanField(verbose_name='Open In Window')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
                ('subcategory_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory_child')),
            ],
        ),
    ]
