# Generated by Django 3.2 on 2022-03-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_alter_footerbanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybanner',
            name='first_caption',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption 1'),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='last_captiop',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caption 2'),
        ),
    ]
