# Generated by Django 3.2 on 2022-03-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_brand_subcategory_child'),
        ('banner', '0005_auto_20220326_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybanner',
            name='subcategory_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subcategory_child'),
        ),
    ]
