# Generated by Django 3.2 on 2022-03-26 10:36

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_alter_categorybanner_subcategory_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='fav_icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='FavIcon')),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='main_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='MainLogo')),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categorybanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/banner/category_banner'),
        ),
        migrations.AlterField(
            model_name='footerbanner',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product/banner/footer_banner'),
        ),
    ]
