# Generated by Django 3.2 on 2022-03-29 02:06

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_auto_20220326_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybanner',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product/banner/category_banner'),
        ),
    ]
